config/routes.rb
Wemote::Application.routes.draw do
  get "searches/index"

  root 'playlists#new'

  resources :playlists do
    get 'search', on: :member
    get 'next_track', on: :member
    get 'track_list', on: :member
  end
  
  resources :searches, only: [:index]

  resources :playlist_invites, only: [:create]

  

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  validates :name, presence: true
  validates :tracks, presence: true,
    unless: Proc.new { |p| p.tracks != nil && p.tracks.empty? }

  scope :non_empty, -> { where("tracks <> ''") }

  def push_track(track)
    tracks_will_change!
    update_attributes tracks: tracks.push(track.id)
  end

  def unshift_track(track)
    tracks_will_change!
    update_attributes tracks: tracks.unshift(track.id)
  end

  def pop_track
    tracks_will_change!
    logger.debug "before popping: "+tracks.to_s
    next_track_id = tracks.shift
    update_attributes tracks: tracks

    next_track = Track.find(next_track_id)
  end

  def remove_track(track)
    if track.nil? then
      return
    else
      tracks_will_change!
      logger.debug "before removing track: "+tracks.to_s
      tracks.delete(track.id.to_s)
      update_attributes tracks: tracks
      track.delete
      logger.debug "after removing tracks: "+tracks.to_s
    end
  end

  def length
    tracks.length
  end
end

app/models/track.rb
class Track < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/playlist_invites_controller.rb
class PlaylistInvitesController < ApplicationController

  def create
    PlaylistInviteMailer.invitation(params[:invitee_emails], params[:playlist_id]).deliver
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

  def show
    @playlist = Playlist.find(params[:id])
    @tracks = Track.find_all_by_id(@playlist.tracks)
    past_playlist_ids_played = cookies[:past_playlist_ids_played].to_s.split(',')
    unless past_playlist_ids_played.include?(@playlist.id.to_s)
      cookies[:past_playlist_ids_played] = past_playlist_ids_played.push(@playlist.id).join(',')
    end
  end

  def new
    @playlist = Playlist.new
    @past_playlists_played = get_past_playlists_played
    @past_playlists_searched = get_past_playlists_searched
  end

  def create
    @playlist = Playlist.new(playlist_params)
    @playlist.tracks = []

    @past_playlists_played = get_past_playlists_played
    @past_playlists_searched = get_past_playlists_searched

    if @playlist.save
      redirect_to playlist_path(@playlist)
    else
      render :new
    end
  end

  def update
    youtube_id = params[:youtube_id]
    playlist_id = params[:playlist_id]
    playlist = Playlist.find(playlist_id)

    if params[:commit] == "Add to Playlist" then
      track = Track.new(youtube_id: youtube_id, title: params[:track_title])
      track.save
      Pusher.trigger(playlist_id, 'track_added', {
        track_id: track.id,
        playlist_id: playlist_id
      })

      logger.debug "add to playlist"
      playlist.push_track(track)
      if playlist.length == 1
        Pusher.trigger(playlist_id, 'first_track_added', {})
      end
    elsif params[:commit] == "Play Now"
      track = Track.new(youtube_id: youtube_id, title: params[:track_title])
      track.save

      logger.debug "play now"
      playlist.unshift_track(track)
      Pusher.trigger(playlist_id, 'play_next_track_now', {})
    elsif params[:commit] == "Remove"
      track = Track.find(params[:track_id])

      logger.debug "remove"
      playlist.remove_track(track)
      Pusher.trigger(playlist_id, 'track_removed', {})
    end

    respond_to do |format|
      format.html { redirect_to playlist_path(playlist) }
      format.js
    end
  end

  def search
    @playlist = Playlist.find(params[:id])
    past_playlist_ids_searched = cookies[:past_playlist_ids_searched].to_s.split(',')
    unless past_playlist_ids_searched.include?(@playlist.id.to_s)
      cookies[:past_playlist_ids_searched] = past_playlist_ids_searched.push(@playlist.id).join(',')
    end
  end

  def next_track
    playlist_id = params[:id]
    playlist = Playlist.find(playlist_id)
    next_youtube_id = playlist.pop_track.youtube_id
    Pusher.trigger(playlist_id, 'track_removed', {})

    respond_to do |format|
      format.json {
        render json: {
          next_youtube_id: next_youtube_id
        }
      }
    end unless next_youtube_id.nil?
  end

  def track_list
    playlist_id = params[:id]
    @playlist = Playlist.find(playlist_id)
    @tracks = Track.find_all_by_id(@playlist.tracks)
    respond_to do |format|
      format.js
    end unless @tracks.nil?
  end

  private 

    def playlist_params
      params.require(:playlist).permit(:name)
    end

    def get_past_playlists_played
      past_playlist_ids_played = cookies[:past_playlist_ids_played].to_s.split(',')
      Playlist.find_all_by_id(past_playlist_ids_played) || []
    end

    def get_past_playlists_searched
      past_playlist_ids_searched = cookies[:past_playlist_ids_searched].to_s.split(',')
      Playlist.find_all_by_id(past_playlist_ids_searched) || []
    end
end

app/controllers/searches_controller.rb
require 'google/api_client'

class SearchesController < ApplicationController
  def index
    @playlist = Playlist.find(params[:playlist_id])
    if params[:search].present?
      @query = params[:search]

      client = Google::APIClient.new(
        key: ENV["GOOGLE_API_KEY"],
        authorization: nil
      )
      youtube = client.discovered_api('youtube', 'v3')
      @results_no_stat = client.execute!(
        api_method: youtube.search.list,
        parameters: {
          part: 'id,snippet',
          q: @query,
          maxResults: 10,
          type: 'video',
        }
      )

      video_ids = @results_no_stat.data.items.collect do |result|
        result.id.videoId
      end

      @results = client.execute!(
        api_method: youtube.videos.list,
        parameters: {
          part: 'id,snippet,statistics',
          id: video_ids.join(",")
        }
      )
    else
      redirect_to action: "search", controller: "playlists", id: @playlist.id
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Wemote"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/playlist_invites_helper.rb
module PlaylistInvitesHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
  def rating_percentage(likes, dislikes)
    total = likes + dislikes
    if total != 0 then
      percentage = likes.to_f/total.to_f * 100
      percentage.round(0).to_s + "%"
    else
      "None"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= yield :head %>
    <%= csrf_meta_tags %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/playlist_invites/create.js.erb
alert("Invitation sent!");

app/views/playlists/_remove_track.html.erb
<%= form_tag playlist_path(playlist),
         method: 'patch',
         remote: true,
         class: "no-margin inline" do %>
  <%= hidden_field_tag :track_id, track.id %>
  <%= hidden_field_tag :playlist_id, playlist.id %>
  <%= submit_tag "Remove", class: "tiny button" %>
<% end %>
<%= track.title %>

app/views/playlists/_track_list.html.erb
<ul class="track-list">
  <% tracks.each do |track| %>
    <li>
      <%= render 'remove_track', track: track, playlist: playlist %>
    </li>
  <% end %>
</ul>

app/views/playlists/new.html.erb
<%  provide :title, 'Create Playlist' %>

<div class="row new-playlist">
  <div class="large-8 columns">
    <h3>Welcome to Wemote.</h3>
    <%= render 'shared/error_messages', record: @playlist %>
    <%= form_for(@playlist) do |f| %>
        <%= f.text_field :name, placeholder: "Enter a name for your new playlist" %>
        <%= f.submit "Create Playlist", class: "button" %>
    <% end %>
  </div>
  <div class="large-4 columns">
    <h6>Playlists you've hosted:</h6>
    <% @past_playlists_played.each do |p| %>
      <%= link_to p.name, playlist_path(p.id), "data-no-turbolink" => true %><br>
    <% end %>
    <br><br>
    <h6>Playlists you've added music to:</h6>
    <% @past_playlists_searched.each do |p| %>
      <%= link_to p.name, search_playlist_path(p.id), "data-no-turbolink" => true %><br>
    <% end %>
  </div>
</div>

app/views/playlists/search.html.erb
<% provide :title, @playlist.name %>
<div class="row search-playlist-container">
  <div class="large-6 large-centered columns">
    <h4>You are on the <span class="color-primary"><%= @playlist.name %></span> playlist.</h4>
    <%= render 'shared/find_song', playlist_id: @playlist.id %>
  </div>
</div>

app/views/playlists/show.html.erb
<% provide :title, @playlist.name %>
<%= javascript_tag do %>
  window.currentPlaylistId = "<%= @playlist.id %>";
<% end %>
<div class="row playlist">
  <div class="large-8 columns">
    <h4 class="color-primary"><%= @playlist.name %></h4>

    <%= link_to "Add songs to this playlist!", search_playlist_path(@playlist.id) %><br>

    <b>Share this link with your friends:</b><br>
    <%= URI.join(root_url, search_playlist_path(@playlist.id)) %><br><br>

    <% content_for :head do %>
      <%= javascript_include_tag 'swfobject' %>
      <%= javascript_include_tag 'jquery.cookie' %>
      <%= javascript_include_tag 'youtube_player' %>
      <script src="http://js.pusher.com/2.1/pusher.min.js"></script>
    <% end %>
    <div id="ytplayercontainer" class="ytplayercontainer">
        You need Flash player 8+ and JavaScript enabled to view this video.
    </div>
  </div>
  <div class="large-4 columns">
    <h6>Send to friends</h6>
    <%= form_tag playlist_invites_path, method: 'post', remote: true do %>
      <p>
        <%= text_area_tag :invitee_emails,
                          params[:invitee_emails],
                          placeholder: "Enter email addresses",
                          class: "invitee-emails" %>
        <%= hidden_field_tag :playlist_id, @playlist.id %>
        <%= submit_tag "Invite", name: nil, class: "small button"%>
      </p>
    <% end %>
  </div>
</div>
<div class="row" id="track-list">
  <%= render 'track_list', tracks: @tracks, playlist: @playlist %>
</div>

app/views/playlists/track_list.js.erb
$("#track-list").html("<%= j(render 'track_list', tracks: @tracks, playlist: @playlist) %>");

app/views/playlists/update.html.erb
Added song!

app/views/searches/index.html.erb
<div class="row">
<h4>Search results for <span class="color-primary"><%= @query %></span><br></h4>
<%= render 'shared/find_song', playlist_id: @playlist.id %>
</div>

<% @results.data.items.each do |result| %>
    <div class="row search-result">
            <div class="small-6 columns">
                <img src="<%= result.snippet.thumbnails.default.url %>">
            </div>
            <div class="small-6 columns">
                <span class="color-primary"><%= result.snippet.title %></span><br>
                <span><%= result.statistics.viewCount %> views</span><br>
                <span>Rating: <%= rating_percentage(result.statistics.likeCount, result.statistics.dislikeCount)%></span><br>
                <%= form_tag playlist_path(@playlist),
                             method: 'patch',
                             remote: true,
                             class: "no-margin inline" do %>
                    <%= hidden_field_tag :youtube_id, result.id %>
                    <%= hidden_field_tag :track_title, result.snippet.title %>
                    <%= hidden_field_tag :playlist_id, @playlist.id %>
                    <%= submit_tag "Add to Playlist", class: "tiny button" %>
                    <%= submit_tag "Play Now", class: "tiny button"  %>
                <% end %>
            </div>
    </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if record.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(record.errors.count, "error") %><br>
      <% record.errors.full_messages.each do |msg| %>
        * <%= msg %><br>
      <% end %><br>
    </div>
  </div>
<% end %>

app/views/shared/_find_song.html.erb
<%= form_tag searches_path, method: 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search], placeholder: "Find a song" %>
    <%= hidden_field_tag :playlist_id, playlist_id %>
    <%= submit_tag "Search", name: nil, class: "small button"%>
  </p>
<% end %>